### ISSUE TITLE
Investigate why confd does not start up during bootup

### ISSUE THREAD

**Issue by limed** [nubisproject/nubis-nat#16]
Sometimes confd doesn't start up at all during bootup

**Comment by gozer** [comment]
Is still an issue? I am quite curious, as that shouldn't happen.

**Comment by limed** [comment]
Yeah it happened once when i was booting up a node, but since then it has not happened. Keeping open for a bit longer to see if its still happening.

**Comment by limed** [comment]
Can't reproduce, closing
