### ISSUE TITLE
Instead of needing confd to inject VPC information, consider using facter

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-nat#56]
From a quick accidental discovery that on ec2, puppet facts do have interesting ec2_* facts, it looks
like the vpc_cird infor you are looking for is actually available as puppet facts..

Could make the whole iptables rules building simpler

```
ec2_mac => 12:3d:ad:a7:c7:2b
ec2_network_interfaces_macs_12:3d:ad:a7:c7:2b_vpc_ipv4_cidr_block => 10.162.12.0/24
```

**Comment by limed** [comment]
fixed in #84
