### ISSUE TITLE
Instead of waiting for the ENI to be available, just steal it

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-nat#57]
This way, during a failover/upgrade, we'll be back up and running much
quicker

--allow-reassociation

**Comment by limed** [comment]
Base on the docs[1] attach-network-interface does not have `--allow-reassociation`

[1]: http://docs.aws.amazon.com/cli/latest/reference/ec2/attach-network-interface.html

**Comment by gozer** [comment]
http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-AssociateAddress.html

**Comment by gozer** [comment]
And if I read that right:l, it's the default for VPC ENis

**Comment by limed** [comment]
Am I missing something?

```
Associates an Elastic IP address with an instance or a network interface. For more information, see Elastic IP Addresses in the Amazon EC2 User Guide for Linux Instances.
```

Your issue here says ENI which is confusing me, if you are trying to attach an EIP then sure but you're saying ENI which doesn't seem to have that option

**Comment by gozer** [comment]
I meant associate the ENI, apologies
